Repository jeffotoni/goexample, pull requests merged in 2022-10, with the labels that each got.

#2 new apis
  api/fiber/Dockerfile
  api/fiber/Makefile
  api/fiber/go.mod
  api/fiber/go.sum
  api/fiber/main.go
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#3 Api Fiber Config
  api/fiber/main.go
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#4 RandomID
  api/fiber/go.mod
  api/fiber/go.sum
  api/fiber/main.go
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#5 k6 sleep
  api/fiber/Makefile
  api/fiber/crypt/crypt.go
  api/fiber/go.mod
  api/fiber/k6/get.js
  api/fiber/main.go
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#6 handler and crypt
  api/fiber/README.md
  api/fiber/handler/handler.go
  api/fiber/main.go
Labels: hacktoberfest, hacktoberfest2022

#10 feat: create http-call example
  aws-route53/get-nameservers.go
  http-call/README.md
  http-call/convert.go
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#11 feat: Add semaphore example.
  patterns/semaphore.go
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#12 map with composite keys
  maps/map4.go
Labels: hacktoberfest-accepted

#13 feat: regex dir
  regex/main.go
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted
